name: Linting
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install    
    - name: Run eslint on changed files
      uses: reviewdog/action-eslint@v1
      with:
        reporter: github-pr-check
        eslint_flags: " -c .eslintrc.js './src/**/*.ts' --max-warnings=0 --ignore-path .gitignore"
