name: Linting

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize


jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install    
    - name: Run eslint on changed files
      uses: tj-actions/eslint-changed-files@v23
      with:
        config_path: ".eslintrc.js"
        ignore_path: ".gitignore"
        file_extensions: './src/**/*.ts'
        extra_args: "--max-warnings=0"
