name: Publish new patch version

# Controls when the action will run. 
on:
  workflow_dispatch:

jobs:
  publish_patch:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install    
    - name: Configure git
      run: git config --global user.email "hello@allinbits.com" &&  git config --global user.name "Github CI"
    - name: Build
      run: pnpm build
    - name: Set version
      run: pnpm version patch
    - name: Commit
      run: git push
    - name: Publish
      run: npm publish

      env:
        NODE_AUTH_TOKEN: ${{secrets.aib_npm_token}}
