name: Semantic PR

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize


jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: "18.x"
        cache: 'pnpm'
    - name: 'Install Deps'
      run: pnpm install
    - name: 'Test'
      run: pnpm coverage
    - name: 'Report Coverage'
      # Set if: always() to also generate the report if tests are failing
      # Only works if you set `reportOnFailure: true` in your vite config as specified above
      if: always() 
      uses:  davelosert/vitest-coverage-report-action@v2
