name: Unit tests

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install    
    - name: Test
      run: pnpm test
